#快速入门学习

In [2]:
import torch.nn as nn
import torch.nn.functional as F
import torch

In [3]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(400, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
    
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)),(2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(x.size()[0], -1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

In [4]:
net = Net()
net

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

In [119]:
params = list(net.parameters())
len(params)

10

In [120]:
for name,parameters in net.named_parameters():
    print(name,':',parameters.size())

conv1.weight : torch.Size([6, 1, 5, 5])
conv1.bias : torch.Size([6])
conv2.weight : torch.Size([16, 6, 5, 5])
conv2.bias : torch.Size([16])
fc1.weight : torch.Size([120, 400])
fc1.bias : torch.Size([120])
fc2.weight : torch.Size([84, 120])
fc2.bias : torch.Size([84])
fc3.weight : torch.Size([10, 84])
fc3.bias : torch.Size([10])


In [130]:
input = torch.rand(1, 1, 32, 32)
input

tensor([[[[0.9513, 0.1093, 0.9682,  ..., 0.0078, 0.4766, 0.2446],
          [0.0557, 0.7372, 0.2865,  ..., 0.5191, 0.3048, 0.1408],
          [0.1185, 0.6232, 0.2900,  ..., 0.1532, 0.0260, 0.1603],
          ...,
          [0.4650, 0.6343, 0.8266,  ..., 0.8655, 0.7047, 0.4117],
          [0.4140, 0.1417, 0.9218,  ..., 0.0671, 0.5497, 0.6754],
          [0.9763, 0.2659, 0.9302,  ..., 0.3597, 0.1949, 0.7750]]]])

In [133]:
out = net.forward(input)
out

tensor([[-0.0499,  0.0261, -0.0247,  0.0880,  0.0321,  0.0525, -0.0984, -0.0518,
          0.1050,  0.0382]], grad_fn=<ThAddmmBackward>)

#tensor学习


In [142]:
# arrange 与 linspace 的区别如下
a = torch.arange(1, 5, 0.5)
b = torch.linspace(1, 5, 6)
print("a:", a)
print("b:", b)

a: tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000])
b: tensor([1.0000, 1.8000, 2.6000, 3.4000, 4.2000, 5.0000])


In [149]:
# 创建tensor 以list
a = [[1,2,3],[3,4,5]]
a = torch.Tensor(a)
print(a.tolist())    # list 与 tensor相互转换

[[1.0, 2.0, 3.0], [3.0, 4.0, 5.0]]


In [167]:
# 以成员元素具体值来创建Tensor
# () [] 创建结果相同
c = torch.Tensor(((1, 3), (2, 3)))
d = torch.Tensor([[1, 3],[2, 3]])

print(c.equal(d))

True


In [174]:
# 区别：分布不同，randn是标准正态，rand是均匀分布
e = torch.randn(5)
f = torch.rand(5)
print(e)
print(f)

tensor([-0.5737, -1.1302, -0.4247, -0.3141,  0.4999])
tensor([0.3303, 0.1534, 0.5441, 0.7393, 0.7936])


In [185]:
# tensor 与 Tensor
# tensor 的操作基本类似于 numpy
scalar = torch.tensor(1)
h = torch.Tensor(1)
print(scalar.shape)
print(h.shape)

vector = torch.tensor([1, 3])     # 不可以torch.tensor(1, 3) 
tensor = torch.Tensor(1, 3)
print(vector.shape)
print(tensor.shape)

torch.Size([])
torch.Size([1])
torch.Size([2])
torch.Size([1, 3])


In [191]:
# tensor 对比 Tensor
empty_tensor = t.tensor([])
empty_Tensor = t.Tensor([])
empty_tensor.shape == empty_Tensor.shape

True

##tensor维度操作：view、squeeze、unsqueeze、resize(可超过、少于本tensor的维度)  
##非inplace操作,对应的 xxx_()为inplace操作

In [251]:
a = torch.arange(0, 4)
b = a.view(-1, 2)           # view、unsqueeze非inplace操作
b.shape

torch.Size([2, 2])

In [270]:
b.shape
c = b.unsqueeze(2)
c.shape     # 在位置1处增加了一维（0/1/2）

torch.Size([2, 2, 1])

In [279]:
b = a.unsqueeze(0).shape


torch.Size([1, 4])
