In [17]:
import torch
import torch.nn as nn

In [11]:
x = torch.tensor(1., requires_grad = True)
w = torch.tensor(2., requires_grad = True)
b = torch.tensor(3., requires_grad = True)

In [13]:
y = w*x + b
y.backward()

In [37]:
print(x.grad)
print(w.grad)
print(b.grad)

None
tensor(1.)
tensor(1.)


In [42]:
x = torch.randn(10, 3)
y = torch.randn(10, 2)
# 实例化模型
linear = nn.Linear(3, 2)
print(linear.weight)
print(linear.bias)
# 实例化目标函数、优化器
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

Parameter containing:
tensor([[ 0.3153, -0.0369,  0.5598],
        [ 0.0326,  0.5248, -0.0057]], requires_grad=True)
Parameter containing:
tensor([0.5059, 0.0343], requires_grad=True)


In [43]:
y_pre = linear(x)
loss = criterion(y, y_pre)

print('before train .loss:', loss.item())

before train .loss: 32.376705169677734


In [44]:
# 开始训练
loss.backward()
print('dw:', linear.weight.grad)
print('db:', linear.bias.grad)

print(linear.weight)
print(linear.bias)

dw: tensor([[ 3.3697, -0.6791,  8.8961],
        [ 0.1031, 14.8054, 11.4115]])
db: tensor([13.3412,  3.5310])
Parameter containing:
tensor([[ 0.3153, -0.0369,  0.5598],
        [ 0.0326,  0.5248, -0.0057]], requires_grad=True)
Parameter containing:
tensor([0.5059, 0.0343], requires_grad=True)


In [45]:
optimizer.step()
print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[ 0.2816, -0.0302,  0.4708],
        [ 0.0316,  0.3768, -0.1199]], requires_grad=True)
Parameter containing:
tensor([ 0.3725, -0.0010], requires_grad=True)


In [46]:
y_pre = linear(x)
loss = criterion(y, y_pre)
print('after 1 train .loss:', loss.item())

after 1 train .loss: 26.88092803955078


Epoch [5/60], Loss: 12.9725
Epoch [10/60], Loss: 5.3567
Epoch [15/60], Loss: 2.2713
Epoch [20/60], Loss: 1.0214
Epoch [25/60], Loss: 0.5151
Epoch [30/60], Loss: 0.3099
Epoch [35/60], Loss: 0.2268
Epoch [40/60], Loss: 0.1932
Epoch [45/60], Loss: 0.1795
Epoch [50/60], Loss: 0.1740
Epoch [55/60], Loss: 0.1717
Epoch [60/60], Loss: 0.1708


<Figure size 640x480 with 1 Axes>